rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install:
  - gem update bundler
before_script:
  - bundle install --gemfile=examples/rails4_root/Gemfile
  - bundle install --gemfile=examples/sinatra_root/Gemfile
branches:
  only:
    - master
